.TH colorsh.sh "bash library" "21-01-2022"  "colorsh.sh man page"
 
.SH NAME
math.sh \- colorsh library written in bash5.17

.SH SYNOPSIS
source "/usr/local/lib/bash5.17/colorsh.sh"

.SH DESCRIPTION
    
.SH VARIABLES
    reset   - return to default

.SH FUNCTIONS

.SH BUGS
No known bugs.

.SH AUTHOR
lazypwny751 - https://github.com/lazypwny751