.TH colorsh.sh "bash library" "21-01-2022"  "colorsh.sh man page"
 
.SH NAME
math.sh \- colorsh library written in bash5.17

.SH SYNOPSIS
source "/usr/local/lib/bash5.17/colorsh.sh"

.SH DESCRIPTION
It is ready for use with a lot of color variables and random color functions with the color billet that will color your script.

.SH VARIABLES
    reset       - return to default
    black       - black
    red         - red
    green       - green
    yellow      - yellow
    blue        - blue
    purple      - purple
    cyan        - cyan
    white       - white
    Bblack      - bold black
    Bred        - bold red
    Bgreen      - bold green
    Byellow     - bold yellow
    Bblue       - bold blue
    Bpurple     - bold purple
    Bcyan       - bold cyan
    Bwhite      - bold white
    Ublack      - ultra black
    Ured        - ultra red
    Ugreen      - ultra green
    Uyellow     - ultra yellow
    Ublue       - ultra blue
    Upurple     - ultra purple
    Ucyan       - ultra cyan
    Uwhite      - ultra what
    BGblack     - black background
    BGred       - red background
    BGgreen     - green background
    BGyellow    - yellow background
    BGblue      - blue background
    BGpurple    - purple background
    BGcyan      - cyan background
    BGwhite     - white background
    Iblack      - intense black
    Ired        - intense read
    Igreen      - intense green
    Iyellow     - intense yellow
    Iblue       - intense blue
    Ipurple     - intense purple
    Icyan       - intense cyan
    Iwhite      - intense white
    BIblack     - bold intense black
    BIred       - bold intense red
    BIgreen     - bold intense green
    BIyellow    - bold intense yellow
    BIblue      - bold intense blue
    BIpurple    - bold intense purple
    BIcyan      - bold intense cyan
    BIwhite     - bold intense white
    BGIblack    - background intense black
    BGIred      - background intense red
    BGIgreen    - background intense green
    BGIyellow   - background intense yellow
    BGIblue     - background intense blue
    BGIpurple   - background intense purple
    BGIcyan     - background intense cyan
    BGIwhite    - background intense white

.SH FUNCTIONS
colorsh:random [OPTION]     - there are one argument called 'cool' and none argument.
colorsh:rainbow [PARAMETER] - just type what do you want to print.

.SH BUGS
No known bugs.

.SH AUTHOR
lazypwny751 - https://github.com/lazypwny751