.TH yamlparser.sh "bash library" "21-01-2022"  "yamlparser.sh man page"
 
.SH NAME
yamlparser.sh \- yamlparser library written in bash5.17

.SH SYNOPSIS
source "/usr/local/lib/bash5.17/yamlparser.sh"

.SH DESCRIPTION
Translate yaml files to bash variable.

.SH FUNCTIONS
yaml:parse2bash:1 [FILE]
yaml:parse2bash:2 [FILE]
yaml:parse2bash:3 [FILE]

.SH BUGS
No known bugs.

.SH AUTHOR
lazypwny751 - https://github.com/lazypwny751